# This is a basic workflow to help you get started with Actions

name: Update Checker

# Controls when the action will run. 
on:
  schedule:
    cron: 0 0 * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download dnsmasq_gfwlist
        run: curl -O https://cokebar.github.io/gfwlist2dnsmasq/dnsmasq_gfwlist.conf

      - name: Compare
        id: compare
        uses: actions/cache@v2
        with:
          path: .compare
          key: compare-${{ hashFiles('./dnsmasq_gfwlist.conf') }}

      - name: Trigger
        if: steps.compare.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
          event-type: Gfwlist Update
